### PR TITLE
Fix module import errors due to prx not being on python search path in pytest tests runing prx on the command line

### PR DESCRIPTION
**Pull request by jtec**

### CODE REVIEW

**Comment by jtec** [comment]
@plutonheaven good find!

Any idea why `PYTHONPATH=src` does not work in CI?

**Comment by plutonheaven** [comment]
I guess it has something to do with defining the paths according to the deployment of the repo on the virtual machine.
Maybe we could keep `PYTHONPATH=src` in `.env` and define it explicitely in the `python-ci.yml` file, just for CI. I think that is what you have tried a few times.

**Comment by jtec** [comment]
@plutonheaven https://github.com/nektos/act is pretty useful to debug CI locally

**Comment by plutonheaven** [comment]
I think the last commit worked. At least, I had no `ModuleNotFoundError` in the CI console, nor on my computer.

**Pull request merged**
