### PR TITLE
Vectorize & refactor

### PR DESCRIPTION
**Pull request by jtec**
This PR uses pandas vector operations to

- Speed up ephemeris computation
- Computation of auxiliary delays such as iono, tropo, Sagnac etc.

It adds unit tests comparing broadcast ephemeris and clock to SP3 precise solutions. 

It also refactors code into subpackages for more modularity.

# Known bugs & limitations
I'll open bug tickets on those once this branch is merged

- GLONASS + SBAS + NAVIC not supported or at least not tested
- JSON output not implemented

### CODE REVIEW

**Comment by jtec** [comment]
@plutonheaven Even without an `.env` file I get locally 

```
23:16:00 ~/repositories/prx speedup $ PYTHONPATH=""
23:16:01 ~/repositories/prx speedup $ echo $PYTHONPATH

23:16:07 ~/repositories/prx speedup $ pipenv shell
Launching subshell in virtual environment...
 . /Users/janbolting/.local/share/virtualenvs/prx-qC74lpao/bin/activate
23:16:13 ~/repositories/prx speedup $  . /Users/janbolting/.local/share/virtualenvs/prx-qC74lpao/bin/activate
(prx) 23:16:13 ~/repositories/prx speedup $ echo $PYTHONPATH
:/Users/janbolting/repositories/prx/src
(prx) 23:16:22 ~/repositories/prx speedup $ 

```

**Comment by plutonheaven** [comment]
It is not working on my Windows and Ubuntu computers, without the `.env`. Also, `echo $PYTHONPATH` does not display anything so I have to enter python and do `import sys` and `sys.path`.

Maybe you [configured something in your venv](https://stackoverflow.com/questions/4757178/how-do-you-set-your-pythonpath-in-an-already-created-virtualenv) such as
- modified a line to your `{venv-root}/bin/activate`
- adding a `.pth` file to `{venv-root}/lib/{python-version}/site-packages`
- modified your `~/.bashrc`

Or you did a [particular configuration from pycharm](https://stackoverflow.com/questions/21236824/unresolved-reference-issue-in-pycharm)

I suggest you do a clean install of the prx repo (git clone, pipenv install) and see if it still works on your computer? Or ask a colleague to do the test?

**Comment by jtec** [comment]
yeah good call, I'll test on another Ubuntu machine

**Comment by plutonheaven** [comment]
Ok to do so. I modified the README in the last commit. Feel free to accept or change the proposition.

**Review by plutonheaven — APPROVED** [review]

**Pull request merged**
